/**
 * Book entity types
 * Represents a book item owned by a specific user
 */
export interface Task {
  id: string;                  // UUID generated by backend
  user_id: string;             // Foreign key to User (enforces data isolation)
  title: string;               // Book title (max 200 chars)
  description: string | null;  // Optional detailed info (max 2000 chars)
  completed: boolean;          // Book reading completion status
  due_date: string | null;    // Optional reading start date (ISO 8601 timestamp)
  due_date_end: string | null; // Optional reading end date (for date range)
  priority: 'low' | 'medium' | 'high' | null;  // Optional priority level
  category: string | null;     // Optional category/genre
  created_at: string;          // ISO 8601 timestamp
  updated_at: string;          // ISO 8601 timestamp
}

// Alias for backward compatibility
export type Book = Task;

/**
 * Input type for creating a new book
 */
export interface CreateTaskInput {
  title: string;
  description?: string;
  due_date?: string | null;
  due_date_end?: string | null;
  priority?: 'low' | 'medium' | 'high' | null;
  category?: string | null;
}

// Alias for backward compatibility
export type CreateBookInput = CreateTaskInput;

/**
 * Input type for updating an existing book (partial update)
 */
export interface UpdateTaskInput {
  title?: string;
  description?: string | null;
  completed?: boolean;
  due_date?: string | null;
  due_date_end?: string | null;
  priority?: 'low' | 'medium' | 'high' | null;
  category?: string | null;
}

// Alias for backward compatibility
export type UpdateBookInput = UpdateTaskInput;
